export interface SubmissionResponse {
  id: string
  salesId: string
  companyId: string
  productId?: string
  applicationId?: string
  customerName: string
  ktp: string
  placeOfBirth?: string
  birthDate?: string
  phoneNumber: string
  whatsAppNumber: string
  email?: string
  submissionAmount: number
  submissionDate: string
  status: string
  address?: string
  residenceAddress?: string
  subdistrict?: string
  city?: string
  postalCode?: number
  gender?: string
  work?: string
  education?: string
  biologicalMotherMaidenName?: string
  emergencyContactName?: string
  emergencyContactPhone?: string
  emergencyContactKtp?: string
  emergencyContactAddress?: string
  dependentsTotal?: number
  npwpNumber?: string
  lengthOfWork?: string
  workAddress?: string
  workSubdistrict?: string
  workCity?: string
  workPostalCode?: number
  monthlyIncome?: number
  annualIncome?: number
  anotherIncome?: number
  verificationReason?: string
  lenderId?: string
  photoKtp?: string
  photoNpwp?: string
  photoSelfie?: string
}
